version: '3.8'

services:
  simpleservice:
    image: droidme/simpleservice:latest
    deploy:
      mode: replicated
      replicas: 1
    networks:
        - traefik-net
    labels:
        - traefik.enable=true
        - traefik.http.routers.simpleservice.rule=Host(`simpleservice.swarm.droidme.io`)
        - traefik.http.routers.simpleservice.entrypoints=web
        - traefik.http.services.simpleservice.loadbalancer.server.port=80
networks:
  traefik-net:
    driver: overlay
    external: true
